gpus: 
  - 0
  - 1
  - 2
  - 3
root: "python_files_sweep/"
sweep_name: "SWEEPFREEZEtest"
models:
  - "lowres_resnet9"
  - "lowres_resnet50"
  - "lowres_densenet121"
  - "lowres_vgg16_bn"
datasets:
  - "cifar10"
number_of_runs: 100